"""add_b2b_matching_fields

Revision ID: 2f5bf907f462
Revises: 
Create Date: 2025-11-30 16:00:50.092355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2f5bf907f462'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expertise_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('growth_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('collaboration_preference', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'hybrid'"), nullable=False))
        batch_op.add_column(sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('current_projects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('current_projects')
        batch_op.drop_column('department')
        batch_op.drop_column('collaboration_preference')
        batch_op.drop_column('growth_skills')
        batch_op.drop_column('expertise_skills')

    # ### end Alembic commands ###
