// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/classes/:class_id": {
    params: {
      "class_id": string;
    };
  };
  "/groups/:group_id": {
    params: {
      "group_id": string;
    };
  };
  "/classes/create": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/groups/create": {
    params: {};
  };
  "/auth/process": {
    params: {};
  };
  "/classes/join": {
    params: {};
  };
  "/profile/edit": {
    params: {};
  };
  "/groups/join": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/profile-setup": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/classes": {
    params: {};
  };
  "/landing": {
    params: {};
  };
  "/groups": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/classes/:class_id" | "/groups/:group_id" | "/classes/create" | "/auth/callback" | "/groups/create" | "/auth/process" | "/classes/join" | "/profile/edit" | "/groups/join" | "/notifications" | "/profile-setup" | "/dashboard" | "/settings" | "/classes" | "/landing" | "/groups" | "/signup" | "/about" | "/login" | "/*";
  };
  "routes/[classes].$[class_id]._index.jsx": {
    id: "routes/[classes].$[class_id]._index";
    page: "/classes/:class_id";
  };
  "routes/[groups].$[group_id]._index.jsx": {
    id: "routes/[groups].$[group_id]._index";
    page: "/groups/:group_id";
  };
  "routes/[classes].[create]._index.jsx": {
    id: "routes/[classes].[create]._index";
    page: "/classes/create";
  };
  "routes/[auth].[callback]._index.jsx": {
    id: "routes/[auth].[callback]._index";
    page: "/auth/callback";
  };
  "routes/[groups].[create]._index.jsx": {
    id: "routes/[groups].[create]._index";
    page: "/groups/create";
  };
  "routes/[auth].[process]._index.jsx": {
    id: "routes/[auth].[process]._index";
    page: "/auth/process";
  };
  "routes/[classes].[join]._index.jsx": {
    id: "routes/[classes].[join]._index";
    page: "/classes/join";
  };
  "routes/[profile].[edit]._index.jsx": {
    id: "routes/[profile].[edit]._index";
    page: "/profile/edit";
  };
  "routes/[groups].[join]._index.jsx": {
    id: "routes/[groups].[join]._index";
    page: "/groups/join";
  };
  "routes/[notifications]._index.jsx": {
    id: "routes/[notifications]._index";
    page: "/notifications";
  };
  "routes/[profile-setup]._index.jsx": {
    id: "routes/[profile-setup]._index";
    page: "/profile-setup";
  };
  "routes/[dashboard]._index.jsx": {
    id: "routes/[dashboard]._index";
    page: "/dashboard";
  };
  "routes/[settings]._index.jsx": {
    id: "routes/[settings]._index";
    page: "/settings";
  };
  "routes/[classes]._index.jsx": {
    id: "routes/[classes]._index";
    page: "/classes";
  };
  "routes/[landing]._index.jsx": {
    id: "routes/[landing]._index";
    page: "/landing";
  };
  "routes/[groups]._index.jsx": {
    id: "routes/[groups]._index";
    page: "/groups";
  };
  "routes/[signup]._index.jsx": {
    id: "routes/[signup]._index";
    page: "/signup";
  };
  "routes/[about]._index.jsx": {
    id: "routes/[about]._index";
    page: "/about";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[classes].$[class_id]._index": typeof import("./app/routes/[classes].$[class_id]._index.jsx");
  "routes/[groups].$[group_id]._index": typeof import("./app/routes/[groups].$[group_id]._index.jsx");
  "routes/[classes].[create]._index": typeof import("./app/routes/[classes].[create]._index.jsx");
  "routes/[auth].[callback]._index": typeof import("./app/routes/[auth].[callback]._index.jsx");
  "routes/[groups].[create]._index": typeof import("./app/routes/[groups].[create]._index.jsx");
  "routes/[auth].[process]._index": typeof import("./app/routes/[auth].[process]._index.jsx");
  "routes/[classes].[join]._index": typeof import("./app/routes/[classes].[join]._index.jsx");
  "routes/[profile].[edit]._index": typeof import("./app/routes/[profile].[edit]._index.jsx");
  "routes/[groups].[join]._index": typeof import("./app/routes/[groups].[join]._index.jsx");
  "routes/[notifications]._index": typeof import("./app/routes/[notifications]._index.jsx");
  "routes/[profile-setup]._index": typeof import("./app/routes/[profile-setup]._index.jsx");
  "routes/[dashboard]._index": typeof import("./app/routes/[dashboard]._index.jsx");
  "routes/[settings]._index": typeof import("./app/routes/[settings]._index.jsx");
  "routes/[classes]._index": typeof import("./app/routes/[classes]._index.jsx");
  "routes/[landing]._index": typeof import("./app/routes/[landing]._index.jsx");
  "routes/[groups]._index": typeof import("./app/routes/[groups]._index.jsx");
  "routes/[signup]._index": typeof import("./app/routes/[signup]._index.jsx");
  "routes/[about]._index": typeof import("./app/routes/[about]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};